version: "3.9"
services:
  redis:
    image: redis
    command: redis-server
    ports:
      - "6379:6379"

  sidekiq:
    depends_on:
      - 'db'
      - 'redis'
    build: .
    volumes:
      - .:/var/www/app/current
    command: bundle exec sidekiq
    environment:
      - REDIS_URL_SIDEKIQ=redis://redis:6379/1

  db:
    image: postgres
    container_name: postgres
    ports:
      - '5432:5432'
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_PASSWORD: "123456"

  base_config:
    image: alpine
    tty: true

  app_config:
    image: alpine
    extends: base_config

  cnab:
    extends:  app_config
    build: .
    container_name: cnab
    depends_on:
      - db
      - redis
    volumes:
      - .:/var/www/app/current
    environment:
      - secret_key_jwt=62950a403661
    ports:
      - "3000:3000"